'use client';

import React, { useEffect, useState } from 'react';
import { createPdfFrame } from '@/utils/pdfFrame';

export type AgreementParty = { name: string; address: string; gstNumber: string; pincode: string; city: string; state: string; phoneNumber: string; email: string };
export type PartnerAgreementType = 'GLAZIA_FABRICATOR' | 'GLAZIA_DEALERSHIP' | 'DEALERSHIP_FABRICATOR';
interface Props { userName: string; completeAddress: string; gstNumber: string; pincode: string; city: string; state: string; phoneNumber: string; email: string; agreementType?: PartnerAgreementType; dealership?: AgreementParty; setBlob: (blob: Blob) => void }

const esc = (v: string) => v.replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c] || c);
const block = (p: AgreementParty) => `${esc(p.name)}<br>${esc(p.email)}<br>GST No: ${esc(p.gstNumber)}<br>${esc(p.address)}, ${esc(p.city)} - ${esc(p.pincode)}, ${esc(p.state)}, India<br>Phone: +91 ${esc(p.phoneNumber)}`;
const glazia: AgreementParty = { name: 'GLAZIA WINDOORS PRIVATE LIMITED', address: 'Kevat Khata No. 361, Rect. No. 21, Killa No. 4/7 0-18, Kherki Daula Village Road', gstNumber: '', pincode: '', city: 'Gurugram', state: 'Haryana', phoneNumber: '9354876670 / 9958053708', email: 'sales@glazia.in' };

const agreementHtml = (type: PartnerAgreementType, second: AgreementParty, dealer?: AgreementParty) => {
  const dealerToFabricator = type === 'DEALERSHIP_FABRICATOR';
  const dealershipAgreement = type === 'GLAZIA_DEALERSHIP';
  const first = dealerToFabricator ? dealer! : glazia;
  const firstRole = dealerToFabricator ? 'Dealership' : 'Glazia';
  const secondRole = dealershipAgreement ? 'Dealership' : 'Fabricator';
  const title = dealerToFabricator ? 'DEALERSHIP–FABRICATOR PARTNER AGREEMENT' : `GLAZIA–${secondRole.toUpperCase()} PARTNER AGREEMENT`;
  const ordering = dealershipAgreement ? 'The Dealership may order goods for its own stock or place an order for direct delivery to a registered Fabricator. Direct-delivery goods shall not enter Dealership stock.' : dealerToFabricator ? "Fabricator orders shall first be checked against Dealership stock. Available quantities are deducted when ordered. If unavailable, the Dealership may order from Glazia for delivery to the Fabricator; those goods shall not enter Dealership stock." : 'The Fabricator shall place orders through the Glazia platform or an approved written channel. Each order is binding only when accepted by Glazia.';
  const inventory = dealershipAgreement ? 'Products ordered for Dealership stock are added to inventory only when marked delivered. The Dealership is responsible for custody, safe storage, insurance and accurate stock records.' : dealerToFabricator ? 'The Dealership shall maintain accurate stock. Fabricator orders fulfilled locally reduce that stock. Authorized manual corrections must remain recorded in the inventory audit ledger.' : 'The Fabricator shall store, handle, fabricate and install products according to current Glazia technical instructions.';
  const payment = dealershipAgreement
    ? 'Prices and discounts are those accepted for each order and may change for future orders. Payments received by Glazia against orders placed by Fabricators registered under the Dealership shall be collected by Glazia and recorded as a credit note in the Dealership’s wallet. The wallet credit may be applied toward amounts payable by the Dealership for orders that it places with Glazia. The Parties shall reconcile Fabricator collections, credit notes, wallet utilization, invoices, taxes, returns, cancellations and other agreed adjustments at the end of each calendar month or on an interim date mutually selected by the Parties. Following reconciliation, the resulting net balance shall be confirmed and settled between Glazia and the Dealership within the mutually agreed period. Overdue amounts may result in suspension of supply, credit or platform access.'
    : 'Prices and discounts are those accepted for each order and may change for future orders. The purchasing Party shall pay invoices, GST, freight and stated charges within the agreed period. Overdue amounts may result in suspension of supply, credit or platform access.';
  const sections = [
    ['1. PURPOSE AND APPOINTMENT', `${firstRole} appoints the ${secondRole} on a non-exclusive basis to market, purchase, supply, fabricate or install approved Glazia aluminium systems, profiles, hardware and accessories for mutually agreed projects and territory. This Agreement creates no employment, franchise, legal partnership or authority to bind the other Party.`],
    ['2. ORDERS AND FULFILMENT', `${ordering} Product, quantity, price, GST, freight, credit and delivery terms in an accepted order or invoice prevail for that transaction.`],
    ['3. INVENTORY AND CUSTODY', `${inventory} Risk passes as stated in the applicable invoice or dispatch document; title remains subject to full payment.`],
    ['4. PRICING, TAXES, PAYMENT AND RECONCILIATION', payment],
    ['5. DELIVERY, INSPECTION AND RETURNS', 'The receiving Party shall inspect quantity and visible condition promptly and report shortages, transit damage or discrepancies in writing within 48 hours. Returns require prior written approval. Delivery dates are estimates unless expressly guaranteed in writing.'],
    ['6. PRODUCT USE AND QUALITY', `The ${secondRole} shall follow current manuals, approved drawings, fabrication tolerances, installation guidance and safety requirements. It shall not alter Glazia branding, represent non-approved goods as genuine, or make warranties beyond official documentation.`],
    ['7. WARRANTY AND CUSTOMER SERVICE', 'Each Party is responsible for its own workmanship, representations and services. Product warranty requires proof of purchase and compliance with storage, fabrication and installation instructions. Misuse, unauthorized modification and improper installation are excluded to the extent permitted by law.'],
    ['8. CONFIDENTIALITY', 'Non-public prices, customer information, drawings, technical data, software access, business plans and commercial terms are confidential. The receiving Party shall use them only for this relationship, limit access to personnel who need to know and protect them with reasonable care. This duty survives termination for three years; trade secrets remain protected while legally confidential.'],
    ['9. INTELLECTUAL PROPERTY AND BRAND', `Glazia retains all rights in its trademarks, catalogues, system designs, drawings, software and technical materials. Permission to use Glazia branding is limited, non-transferable and revocable. The ${secondRole} shall stop using it immediately upon termination.`],
    ['10. COMPLIANCE', 'Each Party shall comply with applicable tax, anti-bribery, competition, consumer protection, labour, environmental, privacy and safety laws; maintain required registrations and licences; and retain accurate transaction records.'],
    ['11. LIABILITY AND INDEMNITY', 'Each Party shall indemnify the other against third-party claims caused by its fraud, wilful misconduct, legal violation, unauthorized representation, negligence or material breach. Neither Party is liable for indirect or consequential loss except where liability cannot lawfully be excluded.'],
    ['12. TERM AND TERMINATION', 'This Agreement begins on execution and continues for three years. Either Party may terminate on 30 days’ written notice, or immediately for uncured material breach, insolvency, fraud, brand misuse or unlawful conduct. Accepted orders, accrued payment, confidentiality, intellectual-property and dispute terms survive.'],
    ['13. FORCE MAJEURE', 'A Party is not liable for delay caused by events beyond reasonable control, provided it promptly notifies the other Party and takes reasonable mitigation steps.'],
    ['14. NOTICES AND DISPUTES', 'Notices must be written and sent to the addresses or emails above. The Parties shall first seek good-faith resolution. Unresolved disputes shall be referred to a sole mutually appointed arbitrator under the Arbitration and Conciliation Act, 1996. The seat and venue shall be Gurugram, Haryana; proceedings shall be in English; Indian law governs; and Gurugram courts have jurisdiction for permitted court proceedings.'],
    ['15. GENERAL', 'This Agreement, accepted orders and referenced policies are the entire understanding on their subject matter. Amendments and waivers must be written. Assignment requires consent except in a lawful business reorganization. Invalid provisions are severed without affecting the remainder. Electronic execution and counterparts are permitted to the extent allowed by law.']
  ];
  return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:18mm}body{font-family:'Times New Roman',serif;font-size:11pt;line-height:1.45;color:#111;max-width:174mm;margin:auto}h1{text-align:center;font-size:16pt;text-decoration:underline}h2{font-size:12pt;margin:18px 0 5px}.party{border:1px solid #bbb;padding:10px;margin:8px 0}.clause{page-break-inside:avoid}.sign{width:100%;margin-top:45px}.sign td{width:50%;vertical-align:top}</style></head><body><h1>${title}</h1><p>This Agreement is executed on <b>${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</b> at <b>${esc(second.state)}</b>.</p><b>BY AND BETWEEN</b><div class="party">${block(first)}<br>(“${firstRole}”)</div><b>AND</b><div class="party">${block(second)}<br>(“${secondRole}”)</div><p>Together, the “Parties”, and individually, a “Party”.</p>${sections.map(([heading, text]) => `<div class="clause"><h2>${heading}</h2><p>${text}</p></div>`).join('')}<p><b>IN WITNESS WHEREOF</b>, the Parties execute this Agreement through authorized representatives.</p><table class="sign"><tr><td><b>${esc(first.name)}</b><br><br>Signature: __________________<br>Name: _____________________<br>Title: ______________________<br>Date: ______________________</td><td><b>${esc(second.name)}</b><br><br>Signature: __________________<br>Name: _____________________<br>Title: ______________________<br>Date: ______________________</td></tr></table><h2>ANNEXURE A — APPROVED SYSTEMS</h2><p>C-Series, E-Series and P-Series Sliding; C4, C5, E131 and E231 Casement; ESF and PSF Slide & Fold; Railing; C1645 Internal Partition; and other products approved in writing.</p></body></html>`;
};

const PartnerAgreement: React.FC<Props> = ({ userName, completeAddress, gstNumber, pincode, city, state, phoneNumber, email, agreementType = 'GLAZIA_FABRICATOR', dealership, setBlob }) => {
  const [url, setUrl] = useState('');
  useEffect(() => {
    let active = true; let objectUrl = ''; let cleanup: (() => void) | undefined;
    const party: AgreementParty = { name: userName, address: completeAddress, gstNumber, pincode, city, state, phoneNumber, email };
    (async () => { try { if (agreementType === 'DEALERSHIP_FABRICATOR' && !dealership) return; const html2pdf = (await import('html2pdf.js')).default; const frame = await createPdfFrame(agreementHtml(agreementType, party, dealership)); cleanup = frame.cleanup; const blob = await html2pdf().set({ margin: .5, image: { type: 'jpeg', quality: .98 }, html2canvas: { scale: 2 }, jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }, pagebreak: { mode: ['css', 'legacy'], avoid: ['tr', '.clause'] } }).from(frame.body).outputPdf('blob'); if (active) { setBlob(blob); objectUrl = URL.createObjectURL(blob); setUrl(objectUrl); } } catch (error) { console.error('Agreement PDF generation failed:', error); } finally { cleanup?.(); } })();
    return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); };
  }, [agreementType, dealership, userName, completeAddress, gstNumber, pincode, city, state, phoneNumber, email, setBlob]);
  return <div className="mt-4">{url ? <a href={url} target="_blank" rel="noopener noreferrer" className="inline-flex rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700">Open Partner Agreement</a> : <div className="text-gray-600">Generating partner agreement…</div>}</div>;
};
export default PartnerAgreement;
